### ISSUE TITLE
straw bug.

### ISSUE THREAD

**Issue by wuchuguang** [simonswain/straw#11]
straw something message not recv

**Comment by wuchuguang** [comment]
// start.js
```
let straw = require('straw');

const strawInstrance = straw.create({nodes_dir:__dirname + "/nodes"});

strawInstrance.add([
    {
        id:'image-task',
        node:'node-image-task',
        input: 'image-out',
        output: 'task-out'
    },
    {
        id:'image-load',
        node:'node-image-load',
        input: 'task-out',
        output: 'image-out'
    }
],function(){
    strawInstrance.start();
});
```

**Comment by wuchuguang** [comment]
// nodes/node-image-load.js
let straw = require('straw');

module.exports = straw.node({
    start: function(done) {
        done(false);
    },
    stop: function(done) {
        done(false);
    },
    process:function(msg, done){
        console.log("load:" + msg);
    }
});

**Comment by wuchuguang** [comment]
// nodes/node-image-task.js
```
let straw = require('straw');

let redis = require('../redis');

const redisInstrance = redis();

module.exports = straw.node({
    opts: {interval: 1000},
    initialize: function(opts, done){
        this.opts.interval = opts && opts.interval || 1000;
        done();
    },
    start: function(done) {
        this.timer = setInterval(this.loadRedis.bind(this), this.opts.interval);
        done(false);
    },
    stop: function(done) {
        clearInterval(this.timer);
        done(false);
    },
    loadRedis: function() {
        redisInstrance.spop(gconst.redis_image_queque, (err, msg)=>{
            if(msg){
                console.log('output msg:' + msg);
                this.output(msg);
            }
        })
    },
    process:function(msg, done){
        console.log(msg);
    }
});
```

**Comment by wuchuguang** [comment]
//print 

 % node start_straw.js
info: 2016-08-12 12:35:22 ADD      image-task
info: 2016-08-12 12:35:22 INIT     image-task 1871
info: 2016-08-12 12:35:22 MESSAGE  image-task           INITIALIZED
info: 2016-08-12 12:35:22 ADD      image-load
info: 2016-08-12 12:35:22 INIT     image-load 1887
info: 2016-08-12 12:35:22 MESSAGE  image-load           INITIALIZED
info: 2016-08-12 12:35:22 MESSAGE  image-task           STARTING
info: 2016-08-12 12:35:22 STARTED  image-task
info: 2016-08-12 12:35:22 MESSAGE  image-task           STARTED
info: 2016-08-12 12:35:22 MESSAGE  image-load           STARTING
info: 2016-08-12 12:35:22 STARTED  image-load
info: 2016-08-12 12:35:22 TOPOLOGY STARTED 
info: 2016-08-12 12:35:22 MESSAGE  image-load           STARTED
info: 2016-08-12 13:43:30 STDOUT   image-task           output msg:gg
info: 2016-08-12 13:43:30 STDOUT   image-load           load:gg
info: 2016-08-12 13:43:39 STDOUT   image-task           output msg:gg
info: 2016-08-12 13:43:40 STDOUT   image-task           output msg:gg
info: 2016-08-12 13:43:41 STDOUT   image-task           output msg:gg
info: 2016-08-12 13:43:42 STDOUT   image-task           output msg:gg
info: 2016-08-12 13:43:43 STDOUT   image-task           output msg:gg
info: 2016-08-12 13:43:44 STDOUT   image-task           output msg:gg
info: 2016-08-12 13:44:41 STDOUT   image-task           output msg:gg



info: 2016-08-12 13:44:47 STDOUT   image-task           output msg:gg

**Comment by wuchuguang** [comment]
task ->print output msg:gg
load ->print once load:gg 
way load.js process(msg, done) not catch message.

**Comment by simonswain** [comment]
Might take me a few days but I'll try and look at this shortly. Thanks for the info.
