### ISSUE TITLE
How to run straw as distributed system

### ISSUE THREAD

**Issue by ahkimkoo** [simonswain/straw#13]
How can i run straw as distributed system, just like storm(java), one spout receive message from MQ, multiple bolt parallel worker. And run processor seperately.

**Comment by yanisIk** [comment]
Is there another node.js framework for realtime data processing ?

This project is really awesome, but I don't know if there's something else such as storm, flink, or samza.

Node.js is really fit for this type of framework but apart from Straw, I can't find anything else.

**Comment by simonswain** [comment]
To run as a distributed system, use a common Redis instance, and have two or more separate machines each with different topoligies. Subscribe the input on one machine to the output on another machine (by pipe name) and it'll just work.

**Comment by simonswain** [comment]
I don't know any other systems doing the same thing in js. Straw is pretty lightweight. Storm etc are heavyweight and will work better for big loads, but I'm guessing take more engineering to set up. Straw is pretty simple to get running.
