### ISSUE TITLE
Debugging with visual studio code.

### ISSUE THREAD

**Issue by mauricionr** [simonswain/straw#4]
Hello @simonswain, I'm trying to debug my straw code, using visual studio code and i'm getting this error

info: 2015-07-16 11:22:55 ADD      ping
info: 2015-07-16 11:22:55 STDERR   ping                 Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Agent.Server.listen (net.js:1267:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3

The code is here,
https://github.com/mauricionr/strawdemos.git

Thanks in advance!

**Comment by simonswain** [comment]
Hi Mauricio -- that error is from you having a process with that port open already. Possibly you have another instance of your app running in another shell, or a process has got stuck running in the background. Have a look at running processes and kill any that are dangling.

I've installed your repo and it runs fine for me

```
~/strawdemos/demo1$ node app
info: 2015-07-17 09:02:51 ADD      ping
info: 2015-07-17 09:02:51 INIT     ping 4028
info: 2015-07-17 09:02:51 MESSAGE  ping                 INITIALIZED
info: 2015-07-17 09:02:51 ADD      count
```

**Comment by mauricionr** [comment]
When I click F5 in visual studio code to start like node app. This error appear in console.

Maybe visualstudio code is  using the same port.

Could be possible?

What you think?

Thanks in advance

**Comment by mauricionr** [comment]
Running in terminal everything it is OK, the problem is visual studio code I guess

**Comment by simonswain** [comment]
Hmm, I'm not sure about Visual Studio, I run it on Linux. Looking at your log more, it seems you are right about VS -- I think it might be trying to attach a debugger to each of the processes that Straw starts up.

Try running from DOS and see if you get a different result, or maybe there is some way to disable the debugger.

**Comment by simonswain** [comment]
@mauricionr Did that fix the problem?

**Comment by mauricionr** [comment]
Not yet, may both are  attaching in the same port as you said.

**Comment by mauricionr** [comment]
I'm hacking on to find a solution.
