### ISSUE TITLE
Using straw with Azure Service Bus

### ISSUE THREAD

**Issue by mauricionr** [simonswain/straw#5]
@simonswain do you know if is possible implements your framework with Azure Service Bus instead Redis..

Tks!

**Comment by simonswain** [comment]
I'm sure it could be possible, Redis is reasonably well abstracted -- you
should be able to modify run / runner and use the nodes without having to
change anything much.

On 23 July 2015 at 03:53, Mauricio nunes dos reis <notifications@github.com>
wrote:

> @simonswain <https://github.com/simonswain> do you know if is possible
> implements your framework with Azure Service Bus instead Redis..
>
> Tks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simonswain/straw/issues/5>.
>



-- 

Simon Swain
+61 418 30 20 20
@simon_swain

**Comment by mauricionr** [comment]
I will try it!

but i guess i should modify tap.js/run.js to adapt redis methods for azure-sb, or create some module for it and apply in these files..

![image](https://cloud.githubusercontent.com/assets/2263551/8855539/0621c1fe-313c-11e5-8df0-fa3289378601.png)

Thanks!
