### ISSUE TITLE
Chalk

### ISSUE THREAD

**Issue by livertonoliveira** [simonswain/straw#8]
Hi, 

I would like to know if is there any way to combine chalk with straw to get my messages colored.

Best regards,
Líverton Oliveira.

**Comment by simonswain** [comment]
Please provide a link to Chalk, I'm not aware of it.

Thanks
Simon

**Comment by livertonli12** [comment]
Hi Simon .

This is Chalk: https://www.npmjs.com/package/chalk   :)

Thanks
Líverton Oliveira.

**Comment by simonswain** [comment]
Would be OK to have Chalk formatting as an option for when sending to console, but I use the output for logging so try to keep it plaintext as possible.
